name: cartridgecounting_project
channels:
  - pytorch
  - defaults
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - colorama=0.4.4
  - cudatoolkit=10.2.89
  - debugpy=1.4.1
  - decorator=5.0.9
  - entrypoints=0.3
  - freetype=2.10.4
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jpeg=9b
  - jupyter_client=7.0.1
  - jupyter_core=4.7.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.40.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openssl=1.1.1l
  - parso=0.8.2
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - prompt-toolkit=3.0.17
  - pygments=2.10.0
  - python=3.9.6
  - python-dateutil=2.8.2
  - pytorch=1.9.0
  - pyzmq=22.2.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - augmentor==0.2.9
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - cycler==0.10.0
    - future==0.18.2
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - idna==3.3
    - imageio==2.9.0
    - importlib-metadata==4.8.2
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.4.3
    - networkx==2.6.3
    - oauthlib==3.1.1
    - opencv-contrib-python==4.5.3.56
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pypylon==1.7.4
    - pypylon==1.7.2
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pywavelets==1.1.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-image==0.18.3
    - scipy==1.7.1
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tifffile==2021.8.30
    - torchsummary==1.5.1
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - zipp==3.6.0
